// wlsmulti.com — product data

const vitamins = [
  {
    name: "ProCare Health 1-per-Day",
    brand: "ProCare Health",
    form: "capsule",
    pillsPerDay: 1,
    price: 26.99,
    pillCount: 30,
    iron: 45,
    b12: 1000,
    surgery: ["bypass", "sleeve", "mini-bypass"],
    coupon: "WLSMULTI15",
    discount: 15,
    url: "https://procarenow.com",
    badge: "Best value"
  },
  {
    name: "BariMelts Multivitamin with Iron",
    brand: "BariMelts",
    form: "dissolving tablet",
    pillsPerDay: 2,
    price: 34.99,
    pillCount: 60,
    iron: 45,
    b12: 1000,
    surgery: ["bypass", "sleeve", "mini-bypass"],
    coupon: "WLSMULTI10",
    discount: 10,
    url: "https://barimelts.com",
    badge: ""
  },
  {
    name: "Celebrate ONE 45",
    brand: "Celebrate Vitamins",
    form: "capsule",
    pillsPerDay: 1,
    price: 29.99,
    pillCount: 30,
    iron: 45,
    b12: 2000,
    surgery: ["bypass", "sleeve", "mini-bypass"],
    coupon: "WLSMULTI10",
    discount: 10,
    url: "https://celebratevitamins.com",
    badge: ""
  },
  {
    name: "Bariatric Advantage Ultra Solo",
    brand: "Bariatric Advantage",
    form: "capsule",
    pillsPerDay: 1,
    price: 39.95,
    pillCount: 30,
    iron: 45,
    b12: 500,
    surgery: ["bypass", "sleeve"],
    coupon: "",
    discount: 0,
    url: "https://bariatricadvantage.com",
    badge: "High thiamin"
  },
  {
    name: "Bariatric Advantage Chewy Bites",
    brand: "Bariatric Advantage",
    form: "chewable",
    pillsPerDay: 2,
    price: 34.95,
    pillCount: 60,
    iron: 0,
    b12: 500,
    surgery: ["sleeve"],
    coupon: "",
    discount: 0,
    url: "https://bariatricadvantage.com",
    badge: "Iron-free"
  },
  {
    name: "Bariatric Fusion One Per Day",
    brand: "Bariatric Fusion",
    form: "chewable",
    pillsPerDay: 1,
    price: 27.99,
    pillCount: 30,
    iron: 45,
    b12: 1000,
    surgery: ["bypass", "sleeve", "mini-bypass"],
    coupon: "",
    discount: 0,
    url: "https://bariatricfusion.com",
    badge: ""
  },
  {
    name: "BariatricPal Multivitamin ONE",
    brand: "BariatricPal",
    form: "chewable",
    pillsPerDay: 1,
    price: 24.99,
    pillCount: 30,
    iron: 45,
    b12: 1000,
    surgery: ["bypass", "sleeve", "mini-bypass"],
    coupon: "",
    discount: 0,
    url: "https://store.bariatricpal.com",
    badge: ""
  },
  {
    name: "NATURELO Bariatric Multivitamin",
    brand: "NATURELO",
    form: "capsule",
    pillsPerDay: 1,
    price: 32.99,
    pillCount: 60,
    iron: 18,
    b12: 1000,
    surgery: ["sleeve"],
    coupon: "",
    discount: 0,
    url: "https://naturelo.com",
    badge: "Whole food"
  },
  {
    name: "BariLife Just One",
    brand: "BariLife",
    form: "capsule",
    pillsPerDay: 1,
    price: 28.95,
    pillCount: 30,
    iron: 45,
    b12: 1500,
    surgery: ["bypass", "mini-bypass"],
    coupon: "",
    discount: 0,
    url: "https://barilife.com",
    badge: ""
  },
  {
    name: "Celebrate Multivitamin Capsule",
    brand: "Celebrate Vitamins",
    form: "capsule",
    pillsPerDay: 2,
    price: 32.99,
    pillCount: 60,
    iron: 22,
    b12: 2000,
    surgery: ["sleeve"],
    coupon: "WLSMULTI10",
    discount: 10,
    url: "https://celebratevitamins.com",
    badge: ""
  }
];
